### ISSUE TITLE
Creeperheal

### ISSUE THREAD

**Issue by ryantheleach** [Manafia-Development/Manafia-Factions#10]
Sorry for contacting you here, your fork didn't have an issues button enabled.

Your update for 1.18 that you just started is forked from nitneleve. 

I just figured I'd let you know that there are 2 far more up to date forks then the original that you may want to base your work from.

https://github.com/Jikoo/CreeperHeal is the current one published to spigot resources. 

but before that, https://github.com/GenkokuServer/CreeperHeal Genkoku also had made significant progress on the original.

**Comment by 71Zombie** [comment]
Oh, thank you for that. I wasnt aware. :)
